### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by newburns** [craigk5n/webcalendar#2]
Is PHP 7.x on the roadmap?

**Comment by craigk5n** [comment]
Yes, I am planning on supporting PHP 7.  There is a php7 patch on sourceforge for 1.2.7, but I have not looked at it yet since I do not yet have a PHP 7 dev environment setup.

**Comment by craigk5n** [comment]
I've made a first attempt at PHP7 compatibility in the devel-1.2.7 branch.  Not yet tested on PHP7 yet.  Most of the code changes were taken from the sourceforge patch for PHP7.

**Comment by craigk5n** [comment]
I've tested most of the master branch of WebCalendar with PHP 7.1, and I don't see any issues.  If you find any specific issues, please create a new issue for it.

**Comment by newburns** [comment]
Updated to the latest Master for WebCalendar.

Using PHP 5.6, webcalendar version 1.3.0 (28 Sep 2008)

Using PHP 7.0 -- Error Log
```bash
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/************/public_html/*********/includes/dbi4php.php:144
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 /home/******/public_html/*********/includes/config.php(244): dbi_connect('localhost', '********', '******************...', '**********', false)
mod_fcgid: stderr: #1 /home/*********/public_html/***********/includes/classes/WebCalendar.class(292): do_config('/home/*********/...')
mod_fcgid: stderr: #2 /home/************/public_html/************/includes/classes/WebCalendar.class(978): WebCalendar->_initConfig()
mod_fcgid: stderr: #3 /home/************/public_html/************/includes/classes/WebCalendar.class(990): WebCalendar->_doInit(1)
mod_fcgid: stderr: #4 /home/************/public_html/************/includes/init.php(64): WebCalendar->initializeFirstPhase()
mod_fcgid: stderr: #5 /home/************/public_html/************/index.php(2): include_once('/home/newburns/...')
mod_fcgid: stderr: #6 {main}
mod_fcgid: stderr:   thrown in /home/************/public_html/************/includes/dbi4php.php on line 144
```

**Comment by newburns** [comment]
Would not reopen
#28
