### ISSUE TITLE
WebCalendar 1.3.0 master will not install under PHP 8

### ISSUE THREAD

**Issue by s22-tech** [craigk5n/webcalendar#238]
Here are a few of the errors I received:

```
Deprecated: Required parameter $date follows optional parameter $type in /home/user/public_html/wc/includes/functions.php on line 2395

Deprecated: Required parameter $time follows optional parameter $description in /home/user/public_html/wc/includes/functions.php on line 6093
  
Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /home/user/public_html/wc/includes/formvars.php:112 Stack trace: #0 /home/user/public_html/wc/install/index.php(157): getGetValue('action') #1 {main} thrown in /home/user/public_html/wc/includes/formvars.php on line 112

Warning: Undefined array key "admin_exists" in /home/user/public_html/wc/install/index.php on line 1527
```

During the installation, when trying to either create or update a db, the URL changes to:
/install/index.php?action=install
but then I get a blank screen and nothing more happens.  No errors are logged.  (Yes, error reporting is turned on.)

**Comment by bigmalletman** [comment]
I have an existing installing on my server running PHP 7.4. I did a trial run of PHP 8.0, but WebCalendar totally falls over with blank white screen. I reverted back to PHP 7.4 for now.

**Comment by craigk5n** [comment]
You will have better luck with the latest code in git.  There are some PHP fixes... not sure about PHP8 though.

**Comment by s22-tech** [comment]
Thanks, Craig, but there are 15 branches listed.  Which one are you referring to?

**Comment by bigmalletman** [comment]
I have synced my existing installation with master. There were only minor differences (magic quote functions).
I get 500 error when trying to open under php 5.0. This is what I see in the error log. I cannot navigate more for obvious reasons.

mod_fcgid: stderr: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /pathtostuff/webcal/includes/functions.php on line 3079
mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /pathtostuff/webcal/includes/xcal.php on line 201
mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /pathtostuff/webcal/includes/gradient.php on line 138

gradiant.php:138 is...

`function can_write_to_dir ($path)
{
  if ( $path { strlen ( $path ) - 1 } == '/' ) //Start function again with tmp file...
    return can_write_to_dir ( $path.uniqid ( mt_rand() ) . '.tmp');`

I think needs to be changed to...

`function can_write_to_dir ($path)
{
  if ( $path [ strlen ( $path ) - 1 ] == '/' ) //Start function again with tmp file...
    return can_write_to_dir ( $path.uniqid ( mt_rand() ) . '.tmp');`

Then I get...

gid: stderr: PHP Fatal error:  Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /home/nblserv/wellsd.com/misc/webcal/includes/functions.php:4
gid: stderr: Stack trace:
gid: stderr: #0 /pathtostuff/webcal/includes/functions.php(4864): abs('')
gid: stderr: #1 /pathtostuff/webcal/includes/functions.php(4647): print_entry(Object(Event), '20210401')
gid: stderr: #2 /pathtostuff/webcal/includes/functions.php(1177): print_date_entries('20210401', '__public__', false, true)
gid: stderr: #3 /pathtostuff/webcal/month.php(79): display_month('04', '2021', false, true)
gid: stderr: #4 {main}
gid: stderr:   thrown in /pathtostuff/webcal/includes/functions.php on line 4864

I'm just guessing, but I'm changing...
`  $catNum = abs( $event->getCategory() );`
to
`  $catNum = abs( (int)$event->getCategory() );`

Now the calendar loads... but only in month.php. week.php throws an error...

gid: stderr: PHP Fatal error:  Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /pathtostuff/webcal/includes/functions.php:3
gid: stderr: Stack trace:, referer: https://pathtostuff/webcal/view_entry.php?id=4497873&date=20210404
gid: stderr: #0 /pathtostuff/webcal/includes/functions.php(3679): abs(''), referer: https://pathtostuff/webcal/view_entry.php?id=4497873&date=20210404
gid: stderr: #1 /pathtostuff/webcal/week.php(110): html_for_event_week_at_a_glance(Object(Event), '20210425'), referer: https://pathtostuff/webcal/view_entry.ph
gid: stderr: #2 {main}, referer: https://pathtostuff/webcal/view_entry.php?id=4497873&date=20210404
gid: stderr:   thrown in /pathtostuff/webcal/includes/functions.php on line 3679, referer: https://pathtostuff/webcal/view_entry.php?id=4497873&date=20210404

so I'm searching the entire functions.php for abs( to make the fix...
Lines 3523, 3679, 4864 need to be cast in (int), I guess...

There may be more errors. Further QA testing is needed for PHP 8.

**Comment by s22-tech** [comment]
I decided to try the webcalendar-bootstrap-ui version, since it seems to be the latest by date, but didn't get much further.  The db seemed to be created successfully, but then I got the white screen again.  

When I enter the main URL, I get taken to ```/install/index.php?action=mismatch&version=UNKNOWN```  instead and the database status says "This appears to be an upgrade from version UNKNOWN to v1.3.0.”  The “Next” button is grayed out, so I click “Update Database” instead.  It takes me to ```/install/index.php?action=install``` and gives me the blank screen again.

Here are few more errors I’ve seen:
```PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /includes/gradient.php on line 138
PHP Deprecated:  crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format. in /login.php on line 113
PHP Deprecated:  crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format. in /includes/user.php on line 112
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /admin.php on line 209
PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /includes/help_list.php on line 73
```

**Comment by s22-tech** [comment]
Hi.  Just checking in.  Any progress on PHP 8 compatibility?

**Comment by NGC6888** [comment]
Hi,
I also use webcalendar parallel on a server with a joomla site. As there is no option to separately set the PHP version for website and webcalendar. Support for PHP8 will be eminent in Future.

**Comment by NGC6888** [comment]
My hoster is strato and it does not allow different php versions for domain and subdomain.

Also PHP7 support will end in near futures so this is no solution of the problem.

**Comment by craigk5n** [comment]
Initial work for PHP 8 is now in master.  I may not have found all the PHP 8 issues, but all the pages I checked are working.
