### ISSUE TITLE
PHP 7.0 throws stderr

### ISSUE THREAD

**Issue by newburns** [craigk5n/webcalendar#28]
Updated to the latest Master for WebCalendar.

Using PHP 5.6, webcalendar version 1.3.0 (28 Sep 2008)

Using PHP 7.0 -- Error Log
```bash
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/************/public_html/*********/includes/dbi4php.php:144
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 /home/******/public_html/*********/includes/config.php(244): dbi_connect('localhost', '********', '******************...', '**********', false)
mod_fcgid: stderr: #1 /home/*********/public_html/***********/includes/classes/WebCalendar.class(292): do_config('/home/*********/...')
mod_fcgid: stderr: #2 /home/************/public_html/************/includes/classes/WebCalendar.class(978): WebCalendar->_initConfig()
mod_fcgid: stderr: #3 /home/************/public_html/************/includes/classes/WebCalendar.class(990): WebCalendar->_doInit(1)
mod_fcgid: stderr: #4 /home/************/public_html/************/includes/init.php(64): WebCalendar->initializeFirstPhase()
mod_fcgid: stderr: #5 /home/************/public_html/************/index.php(2): include_once('/home/newburns/...')
mod_fcgid: stderr: #6 {main}
mod_fcgid: stderr:   thrown in /home/************/public_html/************/includes/dbi4php.php on line 144
```

**Comment by craigk5n** [comment]
For PHP7, I think we need to change the db from mysql to mysqli in include/settings.php.  PHP7 removes mysql functions.

**Comment by newburns** [comment]
That seems to work.
Changing to mysqli in the settiings.php seems to allow usage.
I will watch the log files and report anything else that I may see

**Comment by craigk5n** [comment]
Ok, good to hear. Did you go through the install/upgrade pages?

Wondering if there's a bug in the installer....
