### ISSUE TITLE
Changing to week view results in error

### ISSUE THREAD

**Issue by salocinlofos** [craigk5n/webcalendar#302]
This issue comes up with commit 6183409fce8343278aecf613fc03f5823716956c (master as of today).

When trying to change to week view by either clicking:

- the "week of year" number in top left mini calendar
- the most left column stating the calendar week in month view
- or selecting a week from the pulldown menu from the top menu bar "week"
results in:

> Fatal error: Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in includes/functions.php:3761 Stack trace: #0 includes/functions.php(3761): abs() #1 week.php(110): html_for_event_week_at_a_glance() #2 {main} thrown in includes/functions.php on line 3761

Unfortunately this is the view that I need the most ;-)

**Comment by salocinlofos** [comment]
Okay, the subject of this issue is misleading.

Same kind of errors occur when trying to switch to day view.

> Fatal error: Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in includes/functions.php:3605 Stack trace: #0 includes/functions.php(3605): abs() #1 includes/functions.php(4737): html_for_event_day_at_a_glance() #2 day.php(55): print_day_at_a_glance() #3 {main} thrown in includes/functions.php on line 3605
