### ISSUE TITLE
1.9.10

### ISSUE THREAD

**Issue by JimMlWilson** [craigk5n/webcalendar#500]
Create database never finishes.

**Comment by pflumm** [comment]
It's the same on my Installation !

**Comment by MpmSys** [comment]
I have tried with 1.9.10 and 1.9.8 and in both it creates the database, and fills the config table with 157 lines, but it does not activate the button to go to point 4.

**Comment by MpmSys** [comment]
Log Errors

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ValueError: mb_language(): Argument #1 ($language) must be a valid language, "Spanish" given in /var/www/vhosts/mpmcalendar.online/httpdocs/includes/classes/WebCalendar.php:923\nStack trace:\n#0 /var/www/vhosts/mpmcalendar.online/httpdocs/includes/classes/WebCalendar.php(923): mb_language()\n#1 /var/www/vhosts/mpmcalendar.online/httpdocs/includes/classes/WebCalendar.php(1011): WebCalendar->_initTranslate()\n#2 /var/www/vhosts/mpmcalendar.online/httpdocs/login.php(51): WebCalendar->setLanguage()\n#3 {main}\n thrown in /var/www/vhosts/mpmcalendar.online/httpdocs/includes/classes/WebCalendar.php on line 923'
